from django.urls import path,include
from .views import *
urlpatterns = [
	path('users/bookings',User_bookings.as_view()),
	path('users/bookings-filtered/<str:status>',User_filtered_bookings.as_view()),
	path('users/bookings/<str:booking_uuid>',User_bookings_details.as_view()),
	path('users/bookings/<str:booking_uuid>/change-status',Change_booking_status.as_view()),
	path('users/cart',User_Cart.as_view()),
	path('users/cart/<str:booking_uuid>',CartFunc.as_view()),
	path('users/orders/<str:status>',Orderss.as_view()),
	path('users/order/<str:order_uuid>',Order_details.as_view()),
	path('users/order-add-address/<str:order_uuid>',Order_add_address.as_view()),
	path('users/order-payment/<str:order_uuid>',Order_payment.as_view()),
	path('users/order-callback',Order_callback.as_view()),
	path('users/order/<str:order_uuid>/cancel',Cancel_order.as_view()),
	path('users/coupons/<str:order_uuid>',Coupon_user.as_view()),
	path('users/coupons/<str:order_uuid>/<str:coupon_code>',Coupon_user.as_view()),

	path('users/rapidproto',Rapid_prototyping.as_view()),
	path('users/rapidproto/<str:rapidproto_uuid>',Rapid_prototyping_details.as_view()),

	path('users/consultation',Consultations.as_view()),
	path('users/consultation/<str:consultation_uuid>',Consultation_details.as_view()),
	path('users/contact-us',Contact_uss.as_view()),
	path('users/contact-us/<str:contact_us_uuid>',Contact_us_details.as_view()),

	path('admin/create',CreateAdmin.as_view()),
	path('admin/edit',AdminEdit.as_view()),
	path('admin/delete/<str:admin_uuid>',AdminDelete.as_view()),
	path('admin/all',AdminAll.as_view()),
	path('admin/users/<str:status>',Users_filtered.as_view()),
	path('admin/user-details',Admin_user_details.as_view()),
	path('admin/user-bookings',Admin_user_booking.as_view()),
	path('admin/bookings/<str:status>',Admin_bookings.as_view()),
	path('admin/orders/<str:status>',Admin_orders.as_view()),
	path('admin/order/<str:order_uuid>/change-status',Change_order_status.as_view()),

	path('admin/quotes/<str:status>',Admin_quotes.as_view()),
	path('admin/quote/<str:quotation_uuid>',Admin_quote_details.as_view()),
	path('admin/coupons/<str:status>',Coupon_admin.as_view()),
	path('admin/coupon/<str:coupon_uuid>',Coupon_admin_details.as_view()),

	path('users/',UserCLSOperations.as_view()),
	path('users/editprofile',EditProfile.as_view()),
	path('users/details/<str:uuid>',UserRUDOperations.as_view()),
	path('login',Login.as_view()),
	path('admin-login',AdminLogin.as_view()),
	path('logout',Logout.as_view()),
	path('signup',SignUp.as_view()),
	path('resend-otp',Resend_otp.as_view()),
	path('verify-otp',OtpVerify.as_view()),
	path('forgot-password1',ForgotPassword1.as_view()),
	path('forgot-password2',ForgotPassword2.as_view()),
	path('blogs',BlogsList.as_view()),
	path('blogs/<str:slug>',Blog_details.as_view()),
	path('blogs/<str:blog_uuid>/addcomment',Blog_add_comment.as_view()),
	path('blogs/<str:blog_uuid>/comment/<str:comment_uuid>/delete',Comment_delete.as_view()),
	path('blogs/<str:blog_uuid>/comment/<str:comment_uuid>/replies',View_replies.as_view()),
	path('comment/<str:comment_uuid>/reply',Add_reply.as_view()),
	path('reply/<str:reply_uuid>/delete',Reply_delete.as_view()),
	path('services-all',Services_view_all.as_view()),
	path('bookings-all',Bookings_view_all.as_view()),
]
